import "./globals.css";
import { ThemeProvider } from "@/components/contexts/theme-provider";
import type { Metadata } from "next";
import localFont from "next/font/local";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

const danaVF = localFont({ src: "../../public/fonts/dana/DanaVF.woff2" });

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="fa-IR"
      dir="rtl"
      style={{ colorScheme: "dark" }}
      className={`dark ${danaVF.className}`}
    >
      <body className="antialiased">
        <ThemeProvider>{children}</ThemeProvider>
      </body>
    </html>
  );
}
