import "../../public/fonts/dana/dana.css";
import "./globals.css";
import { ThemeProvider } from "@/components/contexts/theme-provider";
import type { Metadata } from "next";

export const metadata: Metadata = {
  title: "فرانت چپتر | محلی صمیمی برای گفت و گو",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="fa-IR"
      dir="rtl"
      style={{ colorScheme: "dark" }}
      className="dark"
    >
      <body className="bg-background antialiased">
        <ThemeProvider>{children}</ThemeProvider>
      </body>
    </html>
  );
}
